# Generated by Django 4.2.6 on 2023-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=15, null=True)),
                ('messages', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='players',
            old_name='player_id',
            new_name='team_id',
        ),
        migrations.AlterField(
            model_name='teams',
            name='manager_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
