# Generated by Django 4.2.6 on 2023-10-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_messages_rename_player_id_players_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='messages',
        ),
    ]
