# Generated by Django 4.2.6 on 2023-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_players_usertype_teams_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
