# Generated by Django 4.2.6 on 2023-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_players_usertype_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='usertype',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ph_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
