# Generated by Django 4.2.6 on 2023-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_players_team_id_alter_teams_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='usertype',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
